# Generated by Django 5.2 on 2025-09-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_addemployee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addemployee',
            name='email',
        ),
    ]
