# Generated by Django 5.2 on 2025-09-19 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_wfhrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=20)),
                ('gross_annual_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actual_variable_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('in_hand_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_in_hand', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_variable', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('variable_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='accounts.addemployee')),
            ],
        ),
    ]
