# Generated by Django 5.2.6 on 2025-09-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='in_hand_salary',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='monthly_in_hand',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='monthly_salary',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='monthly_variable',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='variable_pay',
        ),
    ]
