# Generated by Django 5.2.6 on 2025-09-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_salary_in_hand_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='actual_variable_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='gross_annual_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
