# Generated by Django 5.2.6 on 2025-09-30 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_addemployee_actual_variable_pay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='final_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salary',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salary',
            name='present_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='working_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='accounts.addemployee'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='financial_year',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='gross_annual_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
