# Generated by Django 5.2.6 on 2025-09-30 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_salary_final_salary_salary_month_salary_present_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addemployee',
            name='actual_variable_pay',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='gross_annual_salary',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='final_salary',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='month',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='present_days',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='working_days',
        ),
        migrations.RemoveField(
            model_name='salary',
            name='year',
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary', to='accounts.addemployee'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='financial_year',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salary',
            name='gross_annual_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
