# Generated by Django 5.2.6 on 2025-09-30 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_leave_is_approved_alter_leave_leave_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.addemployee')),
                ('leave', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.leave')),
            ],
        ),
    ]
