# Generated by Django 5.2.6 on 2025-09-30 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_leaveattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveAttendance',
        ),
    ]
