# Generated by Django 5.2.6 on 2025-09-30 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_monthlysalary_leave_days_monthlysalary_wfh_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysalary',
            name='leave_days',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='wfh_days',
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
