# Generated by Django 5.2.6 on 2025-10-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_leave_status_alter_leave_user_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('wfh', 'Work From Home'), ('weekend', 'Weekend'), ('holiday', 'Holiday')], default='absent', max_length=20),
        ),
    ]
