# Generated by Django 5.2.6 on 2025-10-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave'), ('wfh', 'Work From Home'), ('comp_off', 'Comp Off'), ('weekend', 'Weekend'), ('holiday', 'Holiday')], default='absent', max_length=20),
        ),
        migrations.AlterField(
            model_name='wfhrequest',
            name='type',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Comp Off', 'Comp Off')], max_length=20),
        ),
    ]
