# Generated by Django 5.2.6 on 2025-10-01 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_attendance_status_alter_wfhrequest_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompOffCarryForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('earned_comp_offs', models.IntegerField(default=0)),
                ('used_comp_offs', models.IntegerField(default=0)),
                ('balance_comp_offs', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_off_balance', to='accounts.addemployee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
