# Generated by Django 5.2.6 on 2025-10-01 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_compoffcarryforward'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompOffBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateField()),
                ('earned_reason', models.TextField()),
                ('balance', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_off_balances', to='accounts.addemployee')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='comp_off_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.compoffbalance'),
        ),
        migrations.CreateModel(
            name='CompOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Earn', 'Earn Comp Off'), ('Use', 'Use Comp Off')], max_length=10)),
                ('work_date', models.DateField(blank=True, null=True)),
                ('work_reason', models.TextField(blank=True, null=True)),
                ('use_date', models.DateField(blank=True, null=True)),
                ('use_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comp_off_to_use', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_requests', to='accounts.compoffbalance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_off_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompOffUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_date', models.DateField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comp_off_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.compoffbalance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_off_usages', to='accounts.addemployee')),
                ('used_for_leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.leave')),
            ],
        ),
        migrations.DeleteModel(
            name='CompOffCarryForward',
        ),
    ]
