# Generated by Django 5.2.6 on 2025-10-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_compoffbalance_attendance_comp_off_used_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='comp_off_used',
        ),
        migrations.RemoveField(
            model_name='compoffusage',
            name='comp_off_balance',
        ),
        migrations.RemoveField(
            model_name='compoffrequest',
            name='comp_off_to_use',
        ),
        migrations.RemoveField(
            model_name='compoffrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='compoffusage',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='compoffusage',
            name='used_for_leave',
        ),
        migrations.DeleteModel(
            name='CompOffBalance',
        ),
        migrations.DeleteModel(
            name='CompOffRequest',
        ),
        migrations.DeleteModel(
            name='CompOffUsage',
        ),
    ]
