# Generated by Django 5.2.6 on 2025-10-02 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_attendance_comp_off_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='comp_off_balance_forward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='comp_off_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='comp_off_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='wfh_days',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CompOffBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('balance', models.IntegerField(default=0)),
                ('earned_this_month', models.IntegerField(default=0)),
                ('used_this_month', models.IntegerField(default=0)),
                ('forwarded_from_previous', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_off_balances', to='accounts.addemployee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
