# Generated by Django 5.2.6 on 2025-10-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_monthlysalary_comp_off_balance_forward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysalary',
            name='comp_off_balance_forward',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='comp_off_days',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='comp_off_used',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='leave_days',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='wfh_days',
        ),
        migrations.DeleteModel(
            name='CompOffBalance',
        ),
    ]
