# Generated by Django 5.2.6 on 2025-10-02 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_remove_monthlysalary_comp_off_balance_forward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='comp_off_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='wfh_days',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CompOffBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_comp_off', models.IntegerField(default=0)),
                ('used_comp_off', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comp_off_balance', to='accounts.addemployee')),
            ],
        ),
    ]
