# Generated by Django 5.2.6 on 2025-10-02 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_monthlysalary_comp_off_used_monthlysalary_leave_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysalary',
            name='comp_off_used',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='leave_days',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='wfh_days',
        ),
        migrations.CreateModel(
            name='CompOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.IntegerField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_off_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CompOffBalance',
        ),
    ]
