# Generated by Django 5.2.6 on 2025-10-02 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_monthlysalary_comp_off_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='comp_off_carry_forward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='comp_off_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='comp_off_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='salary_calculation_method',
            field=models.CharField(choices=[('with_comp_off', 'With Comp Off'), ('without_comp_off', 'Without Comp Off')], default='without_comp_off', max_length=20),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='wfh_days',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CompOffBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_hours', models.IntegerField(default=0)),
                ('earned_hours', models.IntegerField(default=0)),
                ('used_hours', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comp_off_balance', to='accounts.addemployee')),
            ],
        ),
    ]
