# Generated by Django 5.2.6 on 2025-10-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_monthlysalary_comp_off_carry_forward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=8),
        ),
    ]
