# Generated by Django 5.2.6 on 2025-10-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_worksession_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='comp_off_request',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='worksession',
            name='request',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='WorkSession',
        ),
    ]
