# Generated by Django 5.2.6 on 2025-10-06 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_compoffrequest_actual_hours_worked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worksession',
            name='notes',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='break_time_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worksession',
            name='end_note',
            field=models.TextField(blank=True, null=True, verbose_name='End of Work Note'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='focus_time_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worksession',
            name='productivity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='worksession',
            name='start_note',
            field=models.TextField(blank=True, null=True, verbose_name='Start of Work Note'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='work_completed',
            field=models.TextField(blank=True, null=True, verbose_name='Work Completed Summary'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('screenshot', 'Screenshot'), ('keyboard', 'Keyboard Activity'), ('mouse', 'Mouse Activity'), ('application', 'Application Switch'), ('break_start', 'Break Started'), ('break_end', 'Break Ended'), ('focus_start', 'Focus Time Started'), ('focus_end', 'Focus Time Ended'), ('note_added', 'Note Added')], max_length=20),
        ),
        migrations.CreateModel(
            name='DailyWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tasks_completed', models.TextField()),
                ('challenges_faced', models.TextField(blank=True, null=True)),
                ('next_day_plan', models.TextField(blank=True, null=True)),
                ('work_start_time_ist', models.TimeField()),
                ('work_end_time_ist', models.TimeField()),
                ('total_work_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tasks_accomplished', models.JSONField(default=list)),
                ('meeting_hours', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('focused_work_hours', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_report', to='accounts.worksession')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
