# Generated by Django 5.2.6 on 2025-10-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_remove_worksession_notes_activitylog_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worksession',
            name='productivity_score',
            field=models.IntegerField(default=50),
        ),
    ]
