# Generated by Django 5.2.7 on 2025-10-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_worksession_productivity_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='half_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('half_day', 'Half Day'), ('absent', 'Absent'), ('leave', 'Leave'), ('wfh', 'Work From Home'), ('comp_off', 'Comp Off'), ('weekend', 'Weekend'), ('holiday', 'Holiday')], default='absent', max_length=20),
        ),
    ]
