# Generated by Django 5.2.7 on 2025-10-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_monthlysalary_half_days_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlysalary',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='comp_off_carry_forward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='final_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='gross_monthly_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='present_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='professional_tax',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='salary_calculation_method',
            field=models.CharField(default='without_comp_off', max_length=50),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='total_working_days',
            field=models.IntegerField(default=0),
        ),
    ]
