# Generated by Django 5.2.7 on 2025-10-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_monthlysalary_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_weekly_offs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='total_days_in_month',
            field=models.IntegerField(default=0),
        ),
    ]
