# Generated by Django 5.2.7 on 2025-10-13 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_modern_work_session_update'),
        ('accounts', '0040_monthlysalary_paid_leaves_and_more'),
    ]

    operations = [
    ]
