# Generated by Django 5.2.7 on 2025-10-14 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_merge_20251013_1627'),
        ('accounts', '0041_monthlysalary_half_day_carry_forward'),
    ]

    operations = [
    ]
