# Generated by Django 5.2.7 on 2025-10-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_merge_20251014_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='half_day_carry_forward',
            new_name='half_day_balance',
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_leave_balance',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='remaining_paid_leaves',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='used_paid_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
