# Generated by Django 5.2.7 on 2025-10-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_rename_half_day_carry_forward_monthlysalary_half_day_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='paid_leaves',
            new_name='carry_forward_half_days',
        ),
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='paid_weekly_offs',
            new_name='carry_forward_paid_leaves',
        ),
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='used_paid_leaves',
            new_name='effective_half_days',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='comp_off_carry_forward',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='remaining_paid_leaves',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='salary_calculation_method',
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='used_paid_leaves_for_half_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='used_paid_leaves_for_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
