# Generated by Django 5.2.7 on 2025-10-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_rename_paid_leaves_monthlysalary_carry_forward_half_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='half_day_balance',
            new_name='half_day_carry_forward',
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='comp_off_carry_forward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_weekly_offs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='remaining_paid_leaves',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='salary_calculation_method',
            field=models.CharField(default='without_comp_off', max_length=50),
        ),
    ]
