# Generated by Django 5.2.7 on 2025-10-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_rename_half_day_balance_monthlysalary_half_day_carry_forward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='current_month_paid_leave',
            field=models.IntegerField(default=1),
        ),
    ]
