# Generated by Django 5.2.7 on 2025-10-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_monthlysalary_current_month_paid_leave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='half_day_carry_forward',
            new_name='used_paid_leaves',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='carry_forward_half_days',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='current_month_paid_leave',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='effective_half_days',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='paid_leave_balance',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='paid_leaves',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='used_paid_leaves_for_half_days',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='used_paid_leaves_for_leaves',
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='current_month_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='carry_forward_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='remaining_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
    ]
