# Generated by Django 5.2.7 on 2025-10-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_rename_half_day_carry_forward_monthlysalary_used_paid_leaves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='carry_forward_half_days',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_leaves',
            field=models.IntegerField(default=1),
        ),
    ]
