# Generated by Django 5.2.7 on 2025-10-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_monthlysalary_carry_forward_half_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_leave_balance',
            field=models.IntegerField(default=1),
        ),
    ]
