# Generated by Django 5.2.7 on 2025-10-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_monthlysalary_paid_leave_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysalary',
            name='paid_leave_balance',
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='effective_half_days',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='unpaid_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
