# Generated by Django 5.2.7 on 2025-10-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_remove_monthlysalary_paid_leave_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_leave_balance',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
