# Generated by Django 5.2.7 on 2025-10-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_monthlysalary_paid_leave_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='used_paid_leaves_for_half_days',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='used_paid_leaves_for_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
