# Generated by Django 5.2.7 on 2025-10-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_monthlysalary_used_paid_leaves_for_half_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='current_month_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='remaining_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
