# Generated by Django 5.2.7 on 2025-10-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_alter_monthlysalary_current_month_paid_leaves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='current_month_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='remaining_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
    ]
