# Generated by Django 5.2.7 on 2025-10-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_alter_monthlysalary_current_month_paid_leaves_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='half_day_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_half_day_am',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_half_day_pm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='comp_off_used_for_half_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='comp_off_used_for_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='salary_calculation_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='used_carry_forward_half_days',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
