# Generated by Django 5.2.7 on 2025-10-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_attendance_half_day_reason_attendance_is_half_day_am_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='comp_off_used',
            new_name='total_comp_off_used',
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='current_month_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='paid_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='remaining_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='salary_calculation_method',
            field=models.CharField(default='new_half_day_comp_off_rules', max_length=50),
        ),
    ]
