# Generated by Django 5.2.7 on 2025-10-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_rename_comp_off_used_monthlysalary_total_comp_off_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='comp_off_used',
            field=models.IntegerField(default=0),
        ),
    ]
