# Generated by Django 5.2.7 on 2025-10-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_monthlysalary_comp_off_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='final_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='gross_monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
