# Generated by Django 5.2.7 on 2025-10-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_alter_monthlysalary_final_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysalary',
            name='comp_off_used',
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='final_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='gross_monthly_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
