# Generated by Django 5.2.7 on 2025-10-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_remove_monthlysalary_comp_off_used_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='comp_off_used_for_half_days',
            new_name='comp_off_used',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='half_day_reason',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_half_day_am',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_half_day_pm',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='comp_off_used_for_leaves',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='salary_calculation_details',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='total_comp_off_used',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='used_carry_forward_half_days',
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='current_month_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='paid_leaves',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='remaining_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='salary_calculation_method',
            field=models.CharField(default='without_comp_off', max_length=50),
        ),
    ]
