# Generated by Django 5.2.7 on 2025-10-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_rename_comp_off_used_for_half_days_monthlysalary_comp_off_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='half_day_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_half_day_am',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_half_day_pm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='comp_off_used_for_half_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='comp_off_used_for_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='salary_calculation_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='total_comp_off_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='used_carry_forward_half_days',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='current_month_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='final_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='gross_monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='paid_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='remaining_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='salary_calculation_method',
            field=models.CharField(default='new_half_day_comp_off_rules', max_length=50),
        ),
    ]
