# Generated by Django 5.2.7 on 2025-10-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_attendance_half_day_reason_attendance_is_half_day_am_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='carry_forward_paid_leaves',
            new_name='new_carry_forward',
        ),
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='effective_half_days',
            new_name='paid_leave_used',
        ),
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='paid_leave_balance',
            new_name='salary_cut_days',
        ),
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='remaining_paid_leaves',
            new_name='unpaid_leave_used',
        ),
        migrations.RenameField(
            model_name='monthlysalary',
            old_name='used_carry_forward_half_days',
            new_name='used_carry_forward',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='comp_off_carry_forward',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='comp_off_used_for_half_days',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='comp_off_used_for_leaves',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='current_month_paid_leaves',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='paid_leaves',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='total_comp_off_used',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='unpaid_leaves',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='used_paid_leaves',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='used_paid_leaves_for_half_days',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='used_paid_leaves_for_leaves',
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='comp_off_used',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='salary_calculation_method',
            field=models.CharField(default='exact_new_rules', max_length=50),
        ),
    ]
