# Generated by Django 5.2.7 on 2025-10-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_rename_carry_forward_paid_leaves_monthlysalary_new_carry_forward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='carry_forward_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='comp_off_carry_forward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='current_month_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='effective_half_days',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_leave_balance',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='paid_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='remaining_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='unpaid_leaves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='used_paid_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='used_paid_leaves_for_half_days',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='used_paid_leaves_for_leaves',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
