# Generated by Django 5.2.7 on 2025-10-16 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_monthlysalary_carry_forward_paid_leaves_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferLetterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('position_applied', models.CharField(max_length=100)),
                ('location_preference', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(max_length=200)),
                ('emergency_phone', models.CharField(max_length=15)),
                ('previous_company', models.CharField(blank=True, max_length=200, null=True)),
                ('total_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('highest_qualification', models.CharField(max_length=200)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('ctc', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
