# Generated by Django 5.2.7 on 2025-10-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_offerletterrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferLetterRequest',
        ),
    ]
