# Generated by Django 5.2.7 on 2025-10-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_addemployee_relieving_letter_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/aadhar/'),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/pan/'),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_documents/photos/'),
        ),
        migrations.AddField(
            model_name='addemployee',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='employee_documents/resumes/'),
        ),
    ]
