# Generated by Django 5.2.7 on 2025-10-17 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_addemployee_aadhar_card_addemployee_aadhar_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addemployee',
            name='aadhar_card',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='pan_card',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='pan_number',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='resume',
        ),
    ]
