# Generated by Django 5.2.7 on 2025-10-17 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_addemployee_aadhar_number_addemployee_blood_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addemployee',
            name='aadhar_number',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='emergency_contact_number',
        ),
        migrations.RemoveField(
            model_name='addemployee',
            name='permanent_address',
        ),
    ]
