# Generated by Django 5.2.7 on 2025-10-17 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_remove_addemployee_aadhar_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_pdf', models.FileField(blank=True, null=True, upload_to='employee_docs/aadhar/')),
                ('pan_pdf', models.FileField(blank=True, null=True, upload_to='employee_docs/pan/')),
                ('passport_pdf', models.FileField(blank=True, null=True, upload_to='employee_docs/passport/')),
                ('tenth_marksheet', models.FileField(blank=True, null=True, upload_to='employee_docs/education/10th/')),
                ('twelfth_marksheet', models.FileField(blank=True, null=True, upload_to='employee_docs/education/12th/')),
                ('highest_qualification_doc', models.FileField(blank=True, null=True, upload_to='employee_docs/education/highest/')),
                ('additional_certifications', models.FileField(blank=True, null=True, upload_to='employee_docs/certifications/')),
                ('skill_certificates', models.FileField(blank=True, null=True, upload_to='employee_docs/skills/')),
                ('company1_offer_letter', models.FileField(blank=True, null=True, upload_to='employee_docs/employment/company1/offer/')),
                ('company1_experience_letter', models.FileField(blank=True, null=True, upload_to='employee_docs/employment/company1/experience/')),
                ('company1_salary_slips', models.FileField(blank=True, null=True, upload_to='employee_docs/employment/company1/salary/')),
                ('company2_offer_letter', models.FileField(blank=True, null=True, upload_to='employee_docs/employment/company2/offer/')),
                ('company2_experience_letter', models.FileField(blank=True, null=True, upload_to='employee_docs/employment/company2/experience/')),
                ('company2_salary_slips', models.FileField(blank=True, null=True, upload_to='employee_docs/employment/company2/salary/')),
                ('bank_document', models.FileField(blank=True, null=True, upload_to='employee_docs/bank/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.addemployee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeePersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('parent_name', models.CharField(blank=True, max_length=200)),
                ('contact_number', models.CharField(max_length=20)),
                ('alternate_number', models.CharField(blank=True, max_length=20)),
                ('personal_email', models.EmailField(max_length=254)),
                ('permanent_address', models.TextField(blank=True)),
                ('current_address', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20)),
                ('blood_group', models.CharField(blank=True, max_length=10)),
                ('aadhar_number', models.CharField(blank=True, max_length=20)),
                ('pan_number', models.CharField(blank=True, max_length=20)),
                ('passport_number', models.CharField(blank=True, max_length=20)),
                ('tenth_marks', models.CharField(blank=True, max_length=20)),
                ('tenth_year', models.CharField(blank=True, max_length=10)),
                ('twelfth_marks', models.CharField(blank=True, max_length=20)),
                ('twelfth_year', models.CharField(blank=True, max_length=10)),
                ('highest_qualification', models.CharField(blank=True, max_length=100)),
                ('highest_qualification_marks', models.CharField(blank=True, max_length=20)),
                ('highest_qualification_year', models.CharField(blank=True, max_length=10)),
                ('university_name', models.CharField(blank=True, max_length=200)),
                ('company1_name', models.CharField(blank=True, max_length=200)),
                ('company1_experience', models.CharField(blank=True, max_length=50)),
                ('company1_from_date', models.DateField(blank=True, null=True)),
                ('company1_to_date', models.DateField(blank=True, null=True)),
                ('company2_name', models.CharField(blank=True, max_length=200)),
                ('company2_experience', models.CharField(blank=True, max_length=50)),
                ('company2_from_date', models.DateField(blank=True, null=True)),
                ('company2_to_date', models.DateField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=20)),
                ('account_holder_name', models.CharField(blank=True, max_length=200)),
                ('pan_number_bank', models.CharField(blank=True, max_length=20)),
                ('uan_number', models.CharField(blank=True, max_length=50)),
                ('esic_number', models.CharField(blank=True, max_length=50)),
                ('tax_regime', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='accounts.addemployee')),
            ],
        ),
    ]
