# Generated by Django 5.2.7 on 2025-10-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_employeedocument_employeepersonalinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeepersonalinfo',
            name='full_name',
        ),
        migrations.AddField(
            model_name='employeepersonalinfo',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employeepersonalinfo',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employeepersonalinfo',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
