# Generated by Django 5.2.7 on 2025-10-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_remove_employeepersonalinfo_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
