# Generated by Django 5.2.7 on 2025-10-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_addemployee_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='company_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='myuser',
            name='notification_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='myuser',
            name='work_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
