# Generated by Django 5.2.7 on 2025-10-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_myuser_company_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='company_settings',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='notification_preferences',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='work_settings',
        ),
    ]
