# Generated by Django 5.2.7 on 2025-10-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_remove_myuser_company_settings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeepersonalinfo',
            name='incomplete_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='employeepersonalinfo',
            name='revision_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeepersonalinfo',
            name='revision_requested',
            field=models.BooleanField(default=False),
        ),
    ]
