# Generated by Django 5.2.7 on 2025-10-23 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_employeepersonalinfo_incomplete_fields_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormRevisionNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('incomplete_fields', models.JSONField(default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_notifications', to='accounts.addemployee')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
