# Generated by Django 5.2.8 on 2025-11-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_monthlysalary_manual_half_day_cut_halfdaymanagement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysalary',
            name='half_day_management',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='manual_half_day_cut',
        ),
        migrations.DeleteModel(
            name='HalfDayManagement',
        ),
    ]
