# Generated by Django 5.2.8 on 2025-11-07 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_remove_monthlysalary_half_day_management_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='manual_half_day_cut',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='manual_half_day_cut_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='HalfDayManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('total_half_days', models.IntegerField()),
                ('remaining_half_days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('decision', models.CharField(choices=[('cut', 'Cut Salary'), ('no_cut', 'No Cut'), ('pending', 'Pending Decision')], default='pending', max_length=20)),
                ('half_days_to_cut', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('salary_cut_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_leave_coverage', models.DecimalField(decimal_places=1, default=0.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.addemployee')),
            ],
            options={
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='half_day_management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_records', to='accounts.halfdaymanagement'),
        ),
    ]
