# Generated by Django 5.2.8 on 2025-11-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0084_remove_monthlysalary_half_day_management_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysalary',
            name='is_manual_adjustment',
            field=models.BooleanField(default=False, help_text='Whether manual adjustment was applied'),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='manual_half_day_cut',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Manual salary cut for half days', max_digits=10),
        ),
        migrations.AddField(
            model_name='monthlysalary',
            name='manual_half_days',
            field=models.IntegerField(default=0, help_text='Manually adjusted half day count'),
        ),
    ]
