# Generated by Django 5.2.8 on 2025-11-08 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_add_manual_half_day_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlysalary',
            name='is_manual_adjustment',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='manual_half_day_cut',
        ),
        migrations.RemoveField(
            model_name='monthlysalary',
            name='manual_half_days',
        ),
    ]
