# Generated by Django 5.2.8 on 2025-11-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_remove_monthlysalary_is_manual_adjustment_and_more'),
    ]

    operations = [
    ]
