# Generated by Django 5.2.8 on 2025-11-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0090_asset_assetassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='purchase_date',
            new_name='given_date',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='notes',
            new_name='submit_notes',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='assigned_date',
            new_name='submitted_date',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='model',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(default='Default description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(default='Assigned', max_length=50),
        ),
    ]
