# Generated by Django 5.2.8 on 2025-11-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0092_asset_asset_condition_asset_asset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
