# Generated by Django 5.2.8 on 2025-11-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0093_addemployee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addemployee',
            name='employee_id',
        ),
    ]
