# Generated by Django 5.2.8 on 2025-11-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0094_remove_addemployee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
