# Generated by Django 5.2.8 on 2025-11-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0095_addemployee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='joining_date',
            field=models.DateField(blank=True, help_text='Employee joining date', null=True),
        ),
    ]
