# Generated by Django 5.2.8 on 2025-11-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_add_joining_date_to_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
