# Generated by Django 5.2.8 on 2025-11-29 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0097_alter_addemployee_phone'),
        ('accounts', '0097_make_phone_unique'),
    ]

    operations = [
    ]
