# Generated by Django 5.2.8 on 2026-03-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0098_merge_20251129_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='compoffrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leave',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wfhrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
