# Generated by Django 5.2.8 on 2026-04-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0099_compoffrequest_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addemployee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
