# Generated by Django 5.2.8 on 2026-04-04 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_addemployee_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompOffUsageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('unpaid_leaves', models.DecimalField(decimal_places=1, max_digits=5)),
                ('comp_off_available_days', models.DecimalField(decimal_places=1, max_digits=5)),
                ('employee_choice', models.CharField(choices=[('pending', 'Pending'), ('use_comp_off', 'Use Comp Off'), ('accept_lop', 'Accept LOP'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_off_usage_requests', to='accounts.addemployee')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
