# Generated by Django 5.2.8 on 2026-04-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0101_comp_off_usage_request'),
    ]

    operations = [
    ]
