# Generated by Django 5.2.8 on 2026-04-04 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0103_recreate_companyleave_saturdayoverride'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='compoffusagerequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='compoffusagerequest',
            name='employee',
        ),
        migrations.DeleteModel(
            name='CompOffUsageRequest',
        ),
    ]
