# Generated by Django 5.2.8 on 2026-04-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0104_delete_companyleave_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyLeave',
        ),
        migrations.DeleteModel(
            name='SaturdayOverride',
        ),
    ]
