# Generated by Django 5.2.8 on 2026-04-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_delete_companyleave_delete_saturdayoverride'),
    ]

    operations = [
    ]
