# Generated by Django 5.2.8 on 2026-04-04 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_alter_companyleave_id_alter_saturdayoverride_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompOffUsageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_off_hours', models.IntegerField()),
                ('for_month', models.IntegerField()),
                ('for_year', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('discarded', 'Discarded')], default='pending', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comp_off_usage_notifications', to='accounts.addemployee')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'for_month', 'for_year')},
            },
        ),
    ]
