# Generated by Django 5.2.8 on 2026-04-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_comp_off_usage_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='antivirus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='domain_updated',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('NA', 'NA')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='hdd_ssd',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='host_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_condition',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor'), ('Damaged', 'Damaged')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='given_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('Stock', 'Stock'), ('In Use', 'In Use'), ('Under Repair', 'Under Repair'), ('Retired', 'Retired'), ('Assigned', 'Assigned'), ('Submitted', 'Submitted'), ('Returned', 'Returned')], default='Stock', max_length=50),
        ),
    ]
