# Generated by Django 5.2.8 on 2026-04-10 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_asset_antivirus_asset_domain_updated_asset_hdd_ssd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='out_date',
        ),
    ]
