# Generated by Django 5.2.7 on 2026-04-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0111_remove_asset_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addemployee',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
